version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      workspace-tools-npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      app-npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /relay
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
    groups:
      relay-npm:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
